# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
xcode_sdk: iphonesimulator10.1

# cache: cocoapods
# gem install cocoapods # Since Travis is not always on latest version
podfile: Examples/Podfile
before_install:
  - gem install xcpretty -N --no-ri --no-rdoc
  - pod install --project-directory=Examples
  - xcrun simctl list # list devices

script:
  - set -o pipefail
  - xcodebuild clean test -workspace Examples/TinyPlayerDemo+Benchmark.xcworkspace -scheme TinyPlayerDemo -destination "platform=iOS Simulator,name=iPhone 7,OS=10.1" ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES | xcpretty
  - pod lib lint

#- xcodebuild clean build -workspace Examples/TinyPlayerDemo+Benchmark.xcworkspace -scheme TinyPlayerDemo -destination "platform=iOS Simulator,name=iPhone 7" ONLY_ACTIVE_ARCH=NO | xcpretty -c || ture
